// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated streaming class types.
//!
//! These types are used during streaming to hold partial results.
//! Field types are already wrapped appropriately (Option, StreamState, etc.)

use baml::{BamlDecode, __internal::serde::Serialize};
use crate::baml_client::types;
use super::*;





#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct CommandRun {



    pub command: Option<String>,



    pub status: Option<types::CommandStatus>,



    pub log: Option<String>,


}



impl ::std::convert::AsRef<CommandRun> for CommandRun {
    fn as_ref(&self) -> &CommandRun {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct HarnessBudget {



    pub tier: Option<types::BudgetTier>,



    pub max_total_tokens: Option<i64>,



    pub max_model_calls: Option<i64>,



    pub max_retries: Option<i64>,



    pub max_runner_minutes: Option<i64>,



    pub max_cost_usd: Option<f64>,



    pub approval_required_above_usd: Option<f64>,


}



impl ::std::convert::AsRef<HarnessBudget> for HarnessBudget {
    fn as_ref(&self) -> &HarnessBudget {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct HarnessOutputs {



    pub branch: Option<String>,



    pub pr: Option<String>,



    pub diff_summary: Option<String>,



    pub validation_log: Option<String>,


}



impl ::std::convert::AsRef<HarnessOutputs> for HarnessOutputs {
    fn as_ref(&self) -> &HarnessOutputs {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct HarnessResult {



    pub job_id: Option<String>,



    pub issue: Option<String>,



    pub lane: Option<types::HarnessLane>,



    pub autonomy_mode: Option<types::AutonomyMode>,



    pub provider: Option<String>,



    pub workspace: Option<String>,



    pub context_bundle_sha: Option<String>,



    pub prompt_pack_version: Option<String>,



    pub budget: Option<HarnessBudget>,



    pub commands_run: Vec<CommandRun>,



    pub changed_files: Vec<String>,



    pub outputs: Option<HarnessOutputs>,



    pub observations: Vec<String>,



    pub decision: Option<String>,



    pub stop_reason: Option<String>,



    pub risk_notes: Vec<String>,


}



impl ::std::convert::AsRef<HarnessResult> for HarnessResult {
    fn as_ref(&self) -> &HarnessResult {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct QaVerdict {



    pub verdict_id: Option<String>,



    pub loop_id: Option<String>,



    pub verdict: Option<String>,



    pub votes: Vec<SwarmVote>,



    pub rationale: Option<String>,



    pub resolved_at: Option<String>,


}



impl ::std::convert::AsRef<QaVerdict> for QaVerdict {
    fn as_ref(&self) -> &QaVerdict {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct SafetyBounds {



    pub thd_max: Option<f64>,



    pub std_dev_max: Option<f64>,



    pub pure_sine_std_dev: Option<f64>,


}



impl ::std::convert::AsRef<SafetyBounds> for SafetyBounds {
    fn as_ref(&self) -> &SafetyBounds {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct SignalTelemetry {



    pub mean: Option<f64>,



    pub std_dev: Option<f64>,



    pub thd: Option<f64>,


}



impl ::std::convert::AsRef<SignalTelemetry> for SignalTelemetry {
    fn as_ref(&self) -> &SignalTelemetry {
        self
    }
}




#[derive(Debug, Clone, Default, BamlDecode, Serialize)]

#[serde(crate = "::baml::__internal::serde")]
pub struct SwarmVote {



    pub agent_id: Option<String>,



    pub role: Option<types::AgentRole>,



    pub value: Option<types::BelnapState>,



    pub reason: Option<String>,



    pub self_trust: Option<f64>,


}



impl ::std::convert::AsRef<SwarmVote> for SwarmVote {
    fn as_ref(&self) -> &SwarmVote {
        self
    }
}

