// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated streaming types (partial data during streaming).
//!
//! Full implementation coming in Phase 6.

mod classes;
mod unions;
mod type_aliases;

pub use classes::*;
pub use unions::*;
pub use type_aliases::*;

use baml::__internal::serde as serde;

/// Streaming variants of types (all fields Optional).
#[derive(Debug, Clone, serde::Serialize)]
#[serde(crate = "::baml::__internal::serde", untagged)]
pub enum StreamTypes {

    CommandRun(CommandRun),

    HarnessBudget(HarnessBudget),

    HarnessOutputs(HarnessOutputs),

    HarnessResult(HarnessResult),

    QaVerdict(QaVerdict),

    SafetyBounds(SafetyBounds),

    SignalTelemetry(SignalTelemetry),

    SwarmVote(SwarmVote),


}

impl baml::KnownTypes for StreamTypes {
    fn as_any(&self) -> &dyn ::std::any::Any {
        self
    }

    fn type_name(&self) -> &'static str {
        match self {

            StreamTypes::CommandRun(_) => "CommandRun",

            StreamTypes::HarnessBudget(_) => "HarnessBudget",

            StreamTypes::HarnessOutputs(_) => "HarnessOutputs",

            StreamTypes::HarnessResult(_) => "HarnessResult",

            StreamTypes::QaVerdict(_) => "QaVerdict",

            StreamTypes::SafetyBounds(_) => "SafetyBounds",

            StreamTypes::SignalTelemetry(_) => "SignalTelemetry",

            StreamTypes::SwarmVote(_) => "SwarmVote",



        }
    }
}

impl<'de> serde::Deserialize<'de> for StreamTypes {
    fn deserialize<D: serde::Deserializer<'de>>(_deserializer: D) -> ::std::result::Result<Self, D::Error> {
        ::std::result::Result::Err(serde::de::Error::custom("StreamTypes is not deserializable, as we cannot disambiguate the type."))
    }
}