/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  AgentRole,  AutonomyMode,  BelnapState,  BudgetTier,  CommandRun,  CommandStatus,  HarnessBudget,  HarnessLane,  HarnessOutputs,  HarnessResult,  QaVerdict,  SafetyBounds,  SignalTelemetry,  SwarmVote } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface CommandRun {
      command?: string | null
      status?: types.CommandStatus | null
      log?: string | null
    }
    export interface HarnessBudget {
      tier?: types.BudgetTier | null
      max_total_tokens?: number | null
      max_model_calls?: number | null
      max_retries?: number | null
      max_runner_minutes?: number | null
      max_cost_usd?: number | null
      approval_required_above_usd?: number | null
    }
    export interface HarnessOutputs {
      branch?: string | null
      pr?: string | null
      diff_summary?: string | null
      validation_log?: string | null
    }
    export interface HarnessResult {
      job_id?: string | null
      issue?: string | null
      lane?: types.HarnessLane | null
      autonomy_mode?: types.AutonomyMode | null
      provider?: string | null
      workspace?: string | null
      context_bundle_sha?: string | null
      prompt_pack_version?: string | null
      budget?: HarnessBudget | null
      commands_run: CommandRun[]
      changed_files: string[]
      outputs?: HarnessOutputs | null
      observations: string[]
      decision?: string | null
      stop_reason?: string | null
      risk_notes: string[]
    }
    export interface QaVerdict {
      verdict_id?: string | null
      loop_id?: string | null
      verdict?: string | null
      votes: SwarmVote[]
      rationale?: string | null
      resolved_at?: string | null
    }
    export interface SafetyBounds {
      thd_max?: number | null
      std_dev_max?: number | null
      pure_sine_std_dev?: number | null
    }
    export interface SignalTelemetry {
      mean?: number | null
      std_dev?: number | null
      thd?: number | null
    }
    export interface SwarmVote {
      agent_id?: string | null
      role?: types.AgentRole | null
      value?: types.BelnapState | null
      reason?: string | null
      self_trust?: number | null
    }
}