/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum AgentRole {
  Generator = "Generator",
  Auditor = "Auditor",
  Architect = "Architect",
  Integrator = "Integrator",
}

export enum AutonomyMode {
  Observe = "Observe",
  Draft = "Draft",
  Patch = "Patch",
  Pr = "Pr",
  Harvest = "Harvest",
}

export enum BelnapState {
  TrueVal = "TrueVal",
  Probable = "Probable",
  Unknown = "Unknown",
  Doubtful = "Doubtful",
  FalseVal = "FalseVal",
  Contradictory = "Contradictory",
}

export enum BudgetTier {
  FreeLocal = "FreeLocal",
  CheapHosted = "CheapHosted",
  PaidAgent = "PaidAgent",
  ManualApproval = "ManualApproval",
}

export enum CommandStatus {
  Passed = "Passed",
  Failed = "Failed",
  Timeout = "Timeout",
  Blocked = "Blocked",
}

export enum HarnessLane {
  Explore = "Explore",
  Shape = "Shape",
  Loop = "Loop",
  Verify = "Verify",
  Govern = "Govern",
}

export interface CommandRun {
  command: string
  status: CommandStatus
  log?: string | null
  
}

export interface HarnessBudget {
  tier: BudgetTier
  max_total_tokens: number
  max_model_calls: number
  max_retries: number
  max_runner_minutes: number
  max_cost_usd: number
  approval_required_above_usd: number
  
}

export interface HarnessOutputs {
  branch?: string | null
  pr?: string | null
  diff_summary?: string | null
  validation_log?: string | null
  
}

export interface HarnessResult {
  job_id: string
  issue: string
  lane: HarnessLane
  autonomy_mode: AutonomyMode
  provider: string
  workspace: string
  context_bundle_sha: string
  prompt_pack_version: string
  budget: HarnessBudget
  commands_run: CommandRun[]
  changed_files: string[]
  outputs: HarnessOutputs
  observations: string[]
  decision: string
  stop_reason: string
  risk_notes: string[]
  
}

export interface QaVerdict {
  verdict_id: string
  loop_id: string
  verdict: string
  votes: SwarmVote[]
  rationale: string
  resolved_at: string
  
}

export interface SafetyBounds {
  thd_max: number
  std_dev_max: number
  pure_sine_std_dev: number
  
}

export interface SignalTelemetry {
  mean: number
  std_dev: number
  thd: number
  
}

export interface SwarmVote {
  agent_id: string
  role: AgentRole
  value: BelnapState
  reason: string
  self_trust: number
  
}
