/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    CommandRun: ClassViewer<'CommandRun', "command" | "status" | "log">;
    
    HarnessBudget: ClassViewer<'HarnessBudget', "tier" | "max_total_tokens" | "max_model_calls" | "max_retries" | "max_runner_minutes" | "max_cost_usd" | "approval_required_above_usd">;
    
    HarnessOutputs: ClassViewer<'HarnessOutputs', "branch" | "pr" | "diff_summary" | "validation_log">;
    
    HarnessResult: ClassViewer<'HarnessResult', "job_id" | "issue" | "lane" | "autonomy_mode" | "provider" | "workspace" | "context_bundle_sha" | "prompt_pack_version" | "budget" | "commands_run" | "changed_files" | "outputs" | "observations" | "decision" | "stop_reason" | "risk_notes">;
    
    QaVerdict: ClassViewer<'QaVerdict', "verdict_id" | "loop_id" | "verdict" | "votes" | "rationale" | "resolved_at">;
    
    SafetyBounds: ClassViewer<'SafetyBounds', "thd_max" | "std_dev_max" | "pure_sine_std_dev">;
    
    SignalTelemetry: ClassViewer<'SignalTelemetry', "mean" | "std_dev" | "thd">;
    
    SwarmVote: ClassViewer<'SwarmVote', "agent_id" | "role" | "value" | "reason" | "self_trust">;
    
    
    AgentRole: EnumViewer<'AgentRole', "Generator" | "Auditor" | "Architect" | "Integrator">;
    
    AutonomyMode: EnumViewer<'AutonomyMode', "Observe" | "Draft" | "Patch" | "Pr" | "Harvest">;
    
    BelnapState: EnumViewer<'BelnapState', "TrueVal" | "Probable" | "Unknown" | "Doubtful" | "FalseVal" | "Contradictory">;
    
    BudgetTier: EnumViewer<'BudgetTier', "FreeLocal" | "CheapHosted" | "PaidAgent" | "ManualApproval">;
    
    CommandStatus: EnumViewer<'CommandStatus', "Passed" | "Failed" | "Timeout" | "Blocked">;
    
    HarnessLane: EnumViewer<'HarnessLane', "Explore" | "Shape" | "Loop" | "Verify" | "Govern">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "CommandRun","HarnessBudget","HarnessOutputs","HarnessResult","QaVerdict","SafetyBounds","SignalTelemetry","SwarmVote",
          ]),
          enums: new Set([
            "AgentRole","AutonomyMode","BelnapState","BudgetTier","CommandStatus","HarnessLane",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.CommandRun = this.tb.classViewer("CommandRun", [
          "command","status","log",
        ]);
        
        this.HarnessBudget = this.tb.classViewer("HarnessBudget", [
          "tier","max_total_tokens","max_model_calls","max_retries","max_runner_minutes","max_cost_usd","approval_required_above_usd",
        ]);
        
        this.HarnessOutputs = this.tb.classViewer("HarnessOutputs", [
          "branch","pr","diff_summary","validation_log",
        ]);
        
        this.HarnessResult = this.tb.classViewer("HarnessResult", [
          "job_id","issue","lane","autonomy_mode","provider","workspace","context_bundle_sha","prompt_pack_version","budget","commands_run","changed_files","outputs","observations","decision","stop_reason","risk_notes",
        ]);
        
        this.QaVerdict = this.tb.classViewer("QaVerdict", [
          "verdict_id","loop_id","verdict","votes","rationale","resolved_at",
        ]);
        
        this.SafetyBounds = this.tb.classViewer("SafetyBounds", [
          "thd_max","std_dev_max","pure_sine_std_dev",
        ]);
        
        this.SignalTelemetry = this.tb.classViewer("SignalTelemetry", [
          "mean","std_dev","thd",
        ]);
        
        this.SwarmVote = this.tb.classViewer("SwarmVote", [
          "agent_id","role","value","reason","self_trust",
        ]);
        
        
        this.AgentRole = this.tb.enumViewer("AgentRole", [
          "Generator","Auditor","Architect","Integrator",
        ]);
        
        this.AutonomyMode = this.tb.enumViewer("AutonomyMode", [
          "Observe","Draft","Patch","Pr","Harvest",
        ]);
        
        this.BelnapState = this.tb.enumViewer("BelnapState", [
          "TrueVal","Probable","Unknown","Doubtful","FalseVal","Contradictory",
        ]);
        
        this.BudgetTier = this.tb.enumViewer("BudgetTier", [
          "FreeLocal","CheapHosted","PaidAgent","ManualApproval",
        ]);
        
        this.CommandStatus = this.tb.enumViewer("CommandStatus", [
          "Passed","Failed","Timeout","Blocked",
        ]);
        
        this.HarnessLane = this.tb.enumViewer("HarnessLane", [
          "Explore","Shape","Loop","Verify","Govern",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}