// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated class types.

use baml::{BamlEncode, BamlDecode, __internal::serde::{Serialize, Deserialize}};
use super::*;




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct CommandRun {
    pub command: String,
    pub status: CommandStatus,
    pub log: Option<String>,
}



impl ::std::convert::AsRef<CommandRun> for CommandRun {
    fn as_ref(&self) -> &CommandRun {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct HarnessBudget {
    pub tier: BudgetTier,
    pub max_total_tokens: i64,
    pub max_model_calls: i64,
    pub max_retries: i64,
    pub max_runner_minutes: i64,
    pub max_cost_usd: f64,
    pub approval_required_above_usd: f64,
}



impl ::std::convert::AsRef<HarnessBudget> for HarnessBudget {
    fn as_ref(&self) -> &HarnessBudget {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct HarnessOutputs {
    pub branch: Option<String>,
    pub pr: Option<String>,
    pub diff_summary: Option<String>,
    pub validation_log: Option<String>,
}



impl ::std::convert::AsRef<HarnessOutputs> for HarnessOutputs {
    fn as_ref(&self) -> &HarnessOutputs {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct HarnessResult {
    pub job_id: String,
    pub issue: String,
    pub lane: HarnessLane,
    pub autonomy_mode: AutonomyMode,
    pub provider: String,
    pub workspace: String,
    pub context_bundle_sha: String,
    pub prompt_pack_version: String,
    pub budget: HarnessBudget,
    pub commands_run: Vec<CommandRun>,
    pub changed_files: Vec<String>,
    pub outputs: HarnessOutputs,
    pub observations: Vec<String>,
    pub decision: String,
    pub stop_reason: String,
    pub risk_notes: Vec<String>,
}



impl ::std::convert::AsRef<HarnessResult> for HarnessResult {
    fn as_ref(&self) -> &HarnessResult {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct QaVerdict {
    pub verdict_id: String,
    pub loop_id: String,
    pub verdict: String,
    pub votes: Vec<SwarmVote>,
    pub rationale: String,
    pub resolved_at: String,
}



impl ::std::convert::AsRef<QaVerdict> for QaVerdict {
    fn as_ref(&self) -> &QaVerdict {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct SafetyBounds {
    pub thd_max: f64,
    pub std_dev_max: f64,
    pub pure_sine_std_dev: f64,
}



impl ::std::convert::AsRef<SafetyBounds> for SafetyBounds {
    fn as_ref(&self) -> &SafetyBounds {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct SignalTelemetry {
    pub mean: f64,
    pub std_dev: f64,
    pub thd: f64,
}



impl ::std::convert::AsRef<SignalTelemetry> for SignalTelemetry {
    fn as_ref(&self) -> &SignalTelemetry {
        self
    }
}




#[derive(Debug, Clone, Default, BamlEncode, BamlDecode, Serialize, Deserialize)]
#[serde(crate = "::baml::__internal::serde")]
pub struct SwarmVote {
    pub agent_id: String,
    pub role: AgentRole,
    pub value: BelnapState,
    pub reason: String,
    pub self_trust: f64,
}



impl ::std::convert::AsRef<SwarmVote> for SwarmVote {
    fn as_ref(&self) -> &SwarmVote {
        self
    }
}

