// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com


//! Generated enum types.

use baml::{BamlEncode, BamlDecode, __internal::serde::{Serialize, Deserialize}};




#[derive(Debug, Clone, PartialEq, Eq, Hash, BamlEncode, BamlDecode, Serialize, Deserialize)]

#[serde(crate = "::baml::__internal::serde")]
pub enum AgentRole {


    Generator,


    Auditor,


    Architect,


    Integrator,


}

impl ::std::default::Default for AgentRole {
    fn default() -> Self {
        
        Self::Generator
        
    }
}

impl ::std::fmt::Display for AgentRole {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {

            Self::Generator => write!(f, "Generator"),

            Self::Auditor => write!(f, "Auditor"),

            Self::Architect => write!(f, "Architect"),

            Self::Integrator => write!(f, "Integrator"),


        }
    }
}

impl ::std::str::FromStr for AgentRole {
    type Err = ();

    fn from_str(s: &str) -> ::std::result::Result<Self, Self::Err> {
        match s {

            "Generator" => ::std::result::Result::Ok(Self::Generator),

            "Auditor" => ::std::result::Result::Ok(Self::Auditor),

            "Architect" => ::std::result::Result::Ok(Self::Architect),

            "Integrator" => ::std::result::Result::Ok(Self::Integrator),


            _ => ::std::result::Result::Err(()),

        }
    }
}

impl ::std::convert::AsRef<AgentRole> for AgentRole {
    fn as_ref(&self) -> &AgentRole {
        self
    }
}




#[derive(Debug, Clone, PartialEq, Eq, Hash, BamlEncode, BamlDecode, Serialize, Deserialize)]

#[serde(crate = "::baml::__internal::serde")]
pub enum AutonomyMode {


    Observe,


    Draft,


    Patch,


    Pr,


    Harvest,


}

impl ::std::default::Default for AutonomyMode {
    fn default() -> Self {
        
        Self::Observe
        
    }
}

impl ::std::fmt::Display for AutonomyMode {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {

            Self::Observe => write!(f, "Observe"),

            Self::Draft => write!(f, "Draft"),

            Self::Patch => write!(f, "Patch"),

            Self::Pr => write!(f, "Pr"),

            Self::Harvest => write!(f, "Harvest"),


        }
    }
}

impl ::std::str::FromStr for AutonomyMode {
    type Err = ();

    fn from_str(s: &str) -> ::std::result::Result<Self, Self::Err> {
        match s {

            "Observe" => ::std::result::Result::Ok(Self::Observe),

            "Draft" => ::std::result::Result::Ok(Self::Draft),

            "Patch" => ::std::result::Result::Ok(Self::Patch),

            "Pr" => ::std::result::Result::Ok(Self::Pr),

            "Harvest" => ::std::result::Result::Ok(Self::Harvest),


            _ => ::std::result::Result::Err(()),

        }
    }
}

impl ::std::convert::AsRef<AutonomyMode> for AutonomyMode {
    fn as_ref(&self) -> &AutonomyMode {
        self
    }
}




#[derive(Debug, Clone, PartialEq, Eq, Hash, BamlEncode, BamlDecode, Serialize, Deserialize)]

#[serde(crate = "::baml::__internal::serde")]
pub enum BelnapState {


    TrueVal,


    Probable,


    Unknown,


    Doubtful,


    FalseVal,


    Contradictory,


}

impl ::std::default::Default for BelnapState {
    fn default() -> Self {
        
        Self::TrueVal
        
    }
}

impl ::std::fmt::Display for BelnapState {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {

            Self::TrueVal => write!(f, "TrueVal"),

            Self::Probable => write!(f, "Probable"),

            Self::Unknown => write!(f, "Unknown"),

            Self::Doubtful => write!(f, "Doubtful"),

            Self::FalseVal => write!(f, "FalseVal"),

            Self::Contradictory => write!(f, "Contradictory"),


        }
    }
}

impl ::std::str::FromStr for BelnapState {
    type Err = ();

    fn from_str(s: &str) -> ::std::result::Result<Self, Self::Err> {
        match s {

            "TrueVal" => ::std::result::Result::Ok(Self::TrueVal),

            "Probable" => ::std::result::Result::Ok(Self::Probable),

            "Unknown" => ::std::result::Result::Ok(Self::Unknown),

            "Doubtful" => ::std::result::Result::Ok(Self::Doubtful),

            "FalseVal" => ::std::result::Result::Ok(Self::FalseVal),

            "Contradictory" => ::std::result::Result::Ok(Self::Contradictory),


            _ => ::std::result::Result::Err(()),

        }
    }
}

impl ::std::convert::AsRef<BelnapState> for BelnapState {
    fn as_ref(&self) -> &BelnapState {
        self
    }
}




#[derive(Debug, Clone, PartialEq, Eq, Hash, BamlEncode, BamlDecode, Serialize, Deserialize)]

#[serde(crate = "::baml::__internal::serde")]
pub enum BudgetTier {


    FreeLocal,


    CheapHosted,


    PaidAgent,


    ManualApproval,


}

impl ::std::default::Default for BudgetTier {
    fn default() -> Self {
        
        Self::FreeLocal
        
    }
}

impl ::std::fmt::Display for BudgetTier {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {

            Self::FreeLocal => write!(f, "FreeLocal"),

            Self::CheapHosted => write!(f, "CheapHosted"),

            Self::PaidAgent => write!(f, "PaidAgent"),

            Self::ManualApproval => write!(f, "ManualApproval"),


        }
    }
}

impl ::std::str::FromStr for BudgetTier {
    type Err = ();

    fn from_str(s: &str) -> ::std::result::Result<Self, Self::Err> {
        match s {

            "FreeLocal" => ::std::result::Result::Ok(Self::FreeLocal),

            "CheapHosted" => ::std::result::Result::Ok(Self::CheapHosted),

            "PaidAgent" => ::std::result::Result::Ok(Self::PaidAgent),

            "ManualApproval" => ::std::result::Result::Ok(Self::ManualApproval),


            _ => ::std::result::Result::Err(()),

        }
    }
}

impl ::std::convert::AsRef<BudgetTier> for BudgetTier {
    fn as_ref(&self) -> &BudgetTier {
        self
    }
}




#[derive(Debug, Clone, PartialEq, Eq, Hash, BamlEncode, BamlDecode, Serialize, Deserialize)]

#[serde(crate = "::baml::__internal::serde")]
pub enum CommandStatus {


    Passed,


    Failed,


    Timeout,


    Blocked,


}

impl ::std::default::Default for CommandStatus {
    fn default() -> Self {
        
        Self::Passed
        
    }
}

impl ::std::fmt::Display for CommandStatus {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {

            Self::Passed => write!(f, "Passed"),

            Self::Failed => write!(f, "Failed"),

            Self::Timeout => write!(f, "Timeout"),

            Self::Blocked => write!(f, "Blocked"),


        }
    }
}

impl ::std::str::FromStr for CommandStatus {
    type Err = ();

    fn from_str(s: &str) -> ::std::result::Result<Self, Self::Err> {
        match s {

            "Passed" => ::std::result::Result::Ok(Self::Passed),

            "Failed" => ::std::result::Result::Ok(Self::Failed),

            "Timeout" => ::std::result::Result::Ok(Self::Timeout),

            "Blocked" => ::std::result::Result::Ok(Self::Blocked),


            _ => ::std::result::Result::Err(()),

        }
    }
}

impl ::std::convert::AsRef<CommandStatus> for CommandStatus {
    fn as_ref(&self) -> &CommandStatus {
        self
    }
}




#[derive(Debug, Clone, PartialEq, Eq, Hash, BamlEncode, BamlDecode, Serialize, Deserialize)]

#[serde(crate = "::baml::__internal::serde")]
pub enum HarnessLane {


    Explore,


    Shape,


    Loop,


    Verify,


    Govern,


}

impl ::std::default::Default for HarnessLane {
    fn default() -> Self {
        
        Self::Explore
        
    }
}

impl ::std::fmt::Display for HarnessLane {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {

            Self::Explore => write!(f, "Explore"),

            Self::Shape => write!(f, "Shape"),

            Self::Loop => write!(f, "Loop"),

            Self::Verify => write!(f, "Verify"),

            Self::Govern => write!(f, "Govern"),


        }
    }
}

impl ::std::str::FromStr for HarnessLane {
    type Err = ();

    fn from_str(s: &str) -> ::std::result::Result<Self, Self::Err> {
        match s {

            "Explore" => ::std::result::Result::Ok(Self::Explore),

            "Shape" => ::std::result::Result::Ok(Self::Shape),

            "Loop" => ::std::result::Result::Ok(Self::Loop),

            "Verify" => ::std::result::Result::Ok(Self::Verify),

            "Govern" => ::std::result::Result::Ok(Self::Govern),


            _ => ::std::result::Result::Err(()),

        }
    }
}

impl ::std::convert::AsRef<HarnessLane> for HarnessLane {
    fn as_ref(&self) -> &HarnessLane {
        self
    }
}

