// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated class builder wrappers for type-safe field access.


/// Wrapper for the `CommandRun` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct CommandRunClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl CommandRunClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("CommandRun is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `command` field builder.
    pub fn property_command(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("command")
            .expect("CommandRun.command is statically defined in .baml and should always be present")
    }


    /// Access the `status` field builder.
    pub fn property_status(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("status")
            .expect("CommandRun.status is statically defined in .baml and should always be present")
    }


    /// Access the `log` field builder.
    pub fn property_log(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("log")
            .expect("CommandRun.log is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `HarnessBudget` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct HarnessBudgetClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl HarnessBudgetClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("HarnessBudget is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `tier` field builder.
    pub fn property_tier(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("tier")
            .expect("HarnessBudget.tier is statically defined in .baml and should always be present")
    }


    /// Access the `max_total_tokens` field builder.
    pub fn property_max_total_tokens(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("max_total_tokens")
            .expect("HarnessBudget.max_total_tokens is statically defined in .baml and should always be present")
    }


    /// Access the `max_model_calls` field builder.
    pub fn property_max_model_calls(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("max_model_calls")
            .expect("HarnessBudget.max_model_calls is statically defined in .baml and should always be present")
    }


    /// Access the `max_retries` field builder.
    pub fn property_max_retries(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("max_retries")
            .expect("HarnessBudget.max_retries is statically defined in .baml and should always be present")
    }


    /// Access the `max_runner_minutes` field builder.
    pub fn property_max_runner_minutes(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("max_runner_minutes")
            .expect("HarnessBudget.max_runner_minutes is statically defined in .baml and should always be present")
    }


    /// Access the `max_cost_usd` field builder.
    pub fn property_max_cost_usd(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("max_cost_usd")
            .expect("HarnessBudget.max_cost_usd is statically defined in .baml and should always be present")
    }


    /// Access the `approval_required_above_usd` field builder.
    pub fn property_approval_required_above_usd(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("approval_required_above_usd")
            .expect("HarnessBudget.approval_required_above_usd is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `HarnessOutputs` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct HarnessOutputsClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl HarnessOutputsClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("HarnessOutputs is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `branch` field builder.
    pub fn property_branch(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("branch")
            .expect("HarnessOutputs.branch is statically defined in .baml and should always be present")
    }


    /// Access the `pr` field builder.
    pub fn property_pr(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("pr")
            .expect("HarnessOutputs.pr is statically defined in .baml and should always be present")
    }


    /// Access the `diff_summary` field builder.
    pub fn property_diff_summary(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("diff_summary")
            .expect("HarnessOutputs.diff_summary is statically defined in .baml and should always be present")
    }


    /// Access the `validation_log` field builder.
    pub fn property_validation_log(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("validation_log")
            .expect("HarnessOutputs.validation_log is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `HarnessResult` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct HarnessResultClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl HarnessResultClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("HarnessResult is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `job_id` field builder.
    pub fn property_job_id(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("job_id")
            .expect("HarnessResult.job_id is statically defined in .baml and should always be present")
    }


    /// Access the `issue` field builder.
    pub fn property_issue(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("issue")
            .expect("HarnessResult.issue is statically defined in .baml and should always be present")
    }


    /// Access the `lane` field builder.
    pub fn property_lane(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("lane")
            .expect("HarnessResult.lane is statically defined in .baml and should always be present")
    }


    /// Access the `autonomy_mode` field builder.
    pub fn property_autonomy_mode(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("autonomy_mode")
            .expect("HarnessResult.autonomy_mode is statically defined in .baml and should always be present")
    }


    /// Access the `provider` field builder.
    pub fn property_provider(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("provider")
            .expect("HarnessResult.provider is statically defined in .baml and should always be present")
    }


    /// Access the `workspace` field builder.
    pub fn property_workspace(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("workspace")
            .expect("HarnessResult.workspace is statically defined in .baml and should always be present")
    }


    /// Access the `context_bundle_sha` field builder.
    pub fn property_context_bundle_sha(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("context_bundle_sha")
            .expect("HarnessResult.context_bundle_sha is statically defined in .baml and should always be present")
    }


    /// Access the `prompt_pack_version` field builder.
    pub fn property_prompt_pack_version(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("prompt_pack_version")
            .expect("HarnessResult.prompt_pack_version is statically defined in .baml and should always be present")
    }


    /// Access the `budget` field builder.
    pub fn property_budget(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("budget")
            .expect("HarnessResult.budget is statically defined in .baml and should always be present")
    }


    /// Access the `commands_run` field builder.
    pub fn property_commands_run(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("commands_run")
            .expect("HarnessResult.commands_run is statically defined in .baml and should always be present")
    }


    /// Access the `changed_files` field builder.
    pub fn property_changed_files(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("changed_files")
            .expect("HarnessResult.changed_files is statically defined in .baml and should always be present")
    }


    /// Access the `outputs` field builder.
    pub fn property_outputs(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("outputs")
            .expect("HarnessResult.outputs is statically defined in .baml and should always be present")
    }


    /// Access the `observations` field builder.
    pub fn property_observations(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("observations")
            .expect("HarnessResult.observations is statically defined in .baml and should always be present")
    }


    /// Access the `decision` field builder.
    pub fn property_decision(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("decision")
            .expect("HarnessResult.decision is statically defined in .baml and should always be present")
    }


    /// Access the `stop_reason` field builder.
    pub fn property_stop_reason(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("stop_reason")
            .expect("HarnessResult.stop_reason is statically defined in .baml and should always be present")
    }


    /// Access the `risk_notes` field builder.
    pub fn property_risk_notes(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("risk_notes")
            .expect("HarnessResult.risk_notes is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `QaVerdict` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct QaVerdictClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl QaVerdictClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("QaVerdict is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `verdict_id` field builder.
    pub fn property_verdict_id(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("verdict_id")
            .expect("QaVerdict.verdict_id is statically defined in .baml and should always be present")
    }


    /// Access the `loop_id` field builder.
    pub fn property_loop_id(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("loop_id")
            .expect("QaVerdict.loop_id is statically defined in .baml and should always be present")
    }


    /// Access the `verdict` field builder.
    pub fn property_verdict(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("verdict")
            .expect("QaVerdict.verdict is statically defined in .baml and should always be present")
    }


    /// Access the `votes` field builder.
    pub fn property_votes(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("votes")
            .expect("QaVerdict.votes is statically defined in .baml and should always be present")
    }


    /// Access the `rationale` field builder.
    pub fn property_rationale(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("rationale")
            .expect("QaVerdict.rationale is statically defined in .baml and should always be present")
    }


    /// Access the `resolved_at` field builder.
    pub fn property_resolved_at(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("resolved_at")
            .expect("QaVerdict.resolved_at is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `SafetyBounds` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct SafetyBoundsClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl SafetyBoundsClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("SafetyBounds is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `thd_max` field builder.
    pub fn property_thd_max(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("thd_max")
            .expect("SafetyBounds.thd_max is statically defined in .baml and should always be present")
    }


    /// Access the `std_dev_max` field builder.
    pub fn property_std_dev_max(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("std_dev_max")
            .expect("SafetyBounds.std_dev_max is statically defined in .baml and should always be present")
    }


    /// Access the `pure_sine_std_dev` field builder.
    pub fn property_pure_sine_std_dev(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("pure_sine_std_dev")
            .expect("SafetyBounds.pure_sine_std_dev is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `SignalTelemetry` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct SignalTelemetryClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl SignalTelemetryClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("SignalTelemetry is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `mean` field builder.
    pub fn property_mean(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("mean")
            .expect("SignalTelemetry.mean is statically defined in .baml and should always be present")
    }


    /// Access the `std_dev` field builder.
    pub fn property_std_dev(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("std_dev")
            .expect("SignalTelemetry.std_dev is statically defined in .baml and should always be present")
    }


    /// Access the `thd` field builder.
    pub fn property_thd(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("thd")
            .expect("SignalTelemetry.thd is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `SwarmVote` class builder.
///
/// Provides type-safe method access to fields defined in the schema.
/// Access fields via methods: `builder.field_name()`

pub struct SwarmVoteClassBuilder {
    inner: ::baml::ClassBuilder,
}

impl SwarmVoteClassBuilder {
    /// Create wrapper from runtime ClassBuilder.
    pub(crate) fn new(inner: ::baml::ClassBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying ClassBuilder.
    pub fn inner(&self) -> &::baml::ClassBuilder {
        &self.inner
    }

    /// Get the class as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("SwarmVote is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Field Accessors (1:1 with schema field names)
    // =========================================================================


    /// Access the `agent_id` field builder.
    pub fn property_agent_id(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("agent_id")
            .expect("SwarmVote.agent_id is statically defined in .baml and should always be present")
    }


    /// Access the `role` field builder.
    pub fn property_role(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("role")
            .expect("SwarmVote.role is statically defined in .baml and should always be present")
    }


    /// Access the `value` field builder.
    pub fn property_value(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("value")
            .expect("SwarmVote.value is statically defined in .baml and should always be present")
    }


    /// Access the `reason` field builder.
    pub fn property_reason(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("reason")
            .expect("SwarmVote.reason is statically defined in .baml and should always be present")
    }


    /// Access the `self_trust` field builder.
    pub fn property_self_trust(&self) -> ::baml::ClassPropertyBuilder {
        self.inner.get_property("self_trust")
            .expect("SwarmVote.self_trust is statically defined in .baml and should always be present")
    }

}

