// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated enum builder wrappers for type-safe value access.


/// Wrapper for the `AgentRole` enum builder.
///
/// Provides type-safe method access to values defined in the schema.
/// Access values via methods: `builder.ValueName()`

pub struct AgentRoleEnumBuilder {
    inner: ::baml::EnumBuilder,
}

impl AgentRoleEnumBuilder {
    /// Create wrapper from runtime EnumBuilder.
    pub(crate) fn new(inner: ::baml::EnumBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying EnumBuilder.
    pub fn inner(&self) -> &::baml::EnumBuilder {
        &self.inner
    }

    /// Get the enum as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("AgentRole is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Value Accessors (1:1 with schema value names)
    // =========================================================================


    /// Access the `Generator` value builder.
    pub fn value_Generator(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Generator")
            .expect("AgentRole.Generator is statically defined in .baml and should always be present")
    }


    /// Access the `Auditor` value builder.
    pub fn value_Auditor(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Auditor")
            .expect("AgentRole.Auditor is statically defined in .baml and should always be present")
    }


    /// Access the `Architect` value builder.
    pub fn value_Architect(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Architect")
            .expect("AgentRole.Architect is statically defined in .baml and should always be present")
    }


    /// Access the `Integrator` value builder.
    pub fn value_Integrator(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Integrator")
            .expect("AgentRole.Integrator is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `AutonomyMode` enum builder.
///
/// Provides type-safe method access to values defined in the schema.
/// Access values via methods: `builder.ValueName()`

pub struct AutonomyModeEnumBuilder {
    inner: ::baml::EnumBuilder,
}

impl AutonomyModeEnumBuilder {
    /// Create wrapper from runtime EnumBuilder.
    pub(crate) fn new(inner: ::baml::EnumBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying EnumBuilder.
    pub fn inner(&self) -> &::baml::EnumBuilder {
        &self.inner
    }

    /// Get the enum as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("AutonomyMode is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Value Accessors (1:1 with schema value names)
    // =========================================================================


    /// Access the `Observe` value builder.
    pub fn value_Observe(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Observe")
            .expect("AutonomyMode.Observe is statically defined in .baml and should always be present")
    }


    /// Access the `Draft` value builder.
    pub fn value_Draft(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Draft")
            .expect("AutonomyMode.Draft is statically defined in .baml and should always be present")
    }


    /// Access the `Patch` value builder.
    pub fn value_Patch(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Patch")
            .expect("AutonomyMode.Patch is statically defined in .baml and should always be present")
    }


    /// Access the `Pr` value builder.
    pub fn value_Pr(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Pr")
            .expect("AutonomyMode.Pr is statically defined in .baml and should always be present")
    }


    /// Access the `Harvest` value builder.
    pub fn value_Harvest(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Harvest")
            .expect("AutonomyMode.Harvest is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `BelnapState` enum builder.
///
/// Provides type-safe method access to values defined in the schema.
/// Access values via methods: `builder.ValueName()`

pub struct BelnapStateEnumBuilder {
    inner: ::baml::EnumBuilder,
}

impl BelnapStateEnumBuilder {
    /// Create wrapper from runtime EnumBuilder.
    pub(crate) fn new(inner: ::baml::EnumBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying EnumBuilder.
    pub fn inner(&self) -> &::baml::EnumBuilder {
        &self.inner
    }

    /// Get the enum as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("BelnapState is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Value Accessors (1:1 with schema value names)
    // =========================================================================


    /// Access the `TrueVal` value builder.
    pub fn value_TrueVal(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("TrueVal")
            .expect("BelnapState.TrueVal is statically defined in .baml and should always be present")
    }


    /// Access the `Probable` value builder.
    pub fn value_Probable(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Probable")
            .expect("BelnapState.Probable is statically defined in .baml and should always be present")
    }


    /// Access the `Unknown` value builder.
    pub fn value_Unknown(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Unknown")
            .expect("BelnapState.Unknown is statically defined in .baml and should always be present")
    }


    /// Access the `Doubtful` value builder.
    pub fn value_Doubtful(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Doubtful")
            .expect("BelnapState.Doubtful is statically defined in .baml and should always be present")
    }


    /// Access the `FalseVal` value builder.
    pub fn value_FalseVal(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("FalseVal")
            .expect("BelnapState.FalseVal is statically defined in .baml and should always be present")
    }


    /// Access the `Contradictory` value builder.
    pub fn value_Contradictory(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Contradictory")
            .expect("BelnapState.Contradictory is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `BudgetTier` enum builder.
///
/// Provides type-safe method access to values defined in the schema.
/// Access values via methods: `builder.ValueName()`

pub struct BudgetTierEnumBuilder {
    inner: ::baml::EnumBuilder,
}

impl BudgetTierEnumBuilder {
    /// Create wrapper from runtime EnumBuilder.
    pub(crate) fn new(inner: ::baml::EnumBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying EnumBuilder.
    pub fn inner(&self) -> &::baml::EnumBuilder {
        &self.inner
    }

    /// Get the enum as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("BudgetTier is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Value Accessors (1:1 with schema value names)
    // =========================================================================


    /// Access the `FreeLocal` value builder.
    pub fn value_FreeLocal(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("FreeLocal")
            .expect("BudgetTier.FreeLocal is statically defined in .baml and should always be present")
    }


    /// Access the `CheapHosted` value builder.
    pub fn value_CheapHosted(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("CheapHosted")
            .expect("BudgetTier.CheapHosted is statically defined in .baml and should always be present")
    }


    /// Access the `PaidAgent` value builder.
    pub fn value_PaidAgent(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("PaidAgent")
            .expect("BudgetTier.PaidAgent is statically defined in .baml and should always be present")
    }


    /// Access the `ManualApproval` value builder.
    pub fn value_ManualApproval(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("ManualApproval")
            .expect("BudgetTier.ManualApproval is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `CommandStatus` enum builder.
///
/// Provides type-safe method access to values defined in the schema.
/// Access values via methods: `builder.ValueName()`

pub struct CommandStatusEnumBuilder {
    inner: ::baml::EnumBuilder,
}

impl CommandStatusEnumBuilder {
    /// Create wrapper from runtime EnumBuilder.
    pub(crate) fn new(inner: ::baml::EnumBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying EnumBuilder.
    pub fn inner(&self) -> &::baml::EnumBuilder {
        &self.inner
    }

    /// Get the enum as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("CommandStatus is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Value Accessors (1:1 with schema value names)
    // =========================================================================


    /// Access the `Passed` value builder.
    pub fn value_Passed(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Passed")
            .expect("CommandStatus.Passed is statically defined in .baml and should always be present")
    }


    /// Access the `Failed` value builder.
    pub fn value_Failed(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Failed")
            .expect("CommandStatus.Failed is statically defined in .baml and should always be present")
    }


    /// Access the `Timeout` value builder.
    pub fn value_Timeout(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Timeout")
            .expect("CommandStatus.Timeout is statically defined in .baml and should always be present")
    }


    /// Access the `Blocked` value builder.
    pub fn value_Blocked(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Blocked")
            .expect("CommandStatus.Blocked is statically defined in .baml and should always be present")
    }

}


/// Wrapper for the `HarnessLane` enum builder.
///
/// Provides type-safe method access to values defined in the schema.
/// Access values via methods: `builder.ValueName()`

pub struct HarnessLaneEnumBuilder {
    inner: ::baml::EnumBuilder,
}

impl HarnessLaneEnumBuilder {
    /// Create wrapper from runtime EnumBuilder.
    pub(crate) fn new(inner: ::baml::EnumBuilder) -> Self {
        Self { inner }
    }

    /// Get the underlying EnumBuilder.
    pub fn inner(&self) -> &::baml::EnumBuilder {
        &self.inner
    }

    /// Get the enum as a type definition.
    pub fn r#type(&self) -> ::baml::TypeDef {
        self.inner.as_type()
            .expect("HarnessLane is statically defined in .baml and should always have a type")
    }


    // =========================================================================
    // Value Accessors (1:1 with schema value names)
    // =========================================================================


    /// Access the `Explore` value builder.
    pub fn value_Explore(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Explore")
            .expect("HarnessLane.Explore is statically defined in .baml and should always be present")
    }


    /// Access the `Shape` value builder.
    pub fn value_Shape(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Shape")
            .expect("HarnessLane.Shape is statically defined in .baml and should always be present")
    }


    /// Access the `Loop` value builder.
    pub fn value_Loop(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Loop")
            .expect("HarnessLane.Loop is statically defined in .baml and should always be present")
    }


    /// Access the `Verify` value builder.
    pub fn value_Verify(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Verify")
            .expect("HarnessLane.Verify is statically defined in .baml and should always be present")
    }


    /// Access the `Govern` value builder.
    pub fn value_Govern(&self) -> ::baml::EnumValueBuilder {
        self.inner.get_value("Govern")
            .expect("HarnessLane.Govern is statically defined in .baml and should always be present")
    }

}

