// This file was generated by BAML: do not edit it.
// Instead, edit the BAML source files.
//
// Learn more at https://docs.boundaryml.com

//! Generated TypeBuilder wrappers for type-safe schema access.

mod classes;
mod enums;

pub use classes::*;
pub use enums::*;

/// TypeBuilder for dynamic type construction.
///
/// This wrapper provides access to the BAML TypeBuilder for creating
/// dynamic types at runtime. Use `TypeBuilder::new()` to create an instance.
///
/// Access schema-defined classes and enums via methods:
/// - `tb.ClassName()` returns the class builder
/// - `tb.EnumName()` returns the enum builder
#[derive(Clone)]
pub struct TypeBuilder {
    inner: ::std::sync::Arc<::baml::TypeBuilder>,
}

impl TypeBuilder {
    /// Create a new TypeBuilder for dynamic type construction.
    ///
    /// # Example
    /// ```ignore
    /// let tb = TypeBuilder::new();
    /// let my_enum = tb.add_enum("MyDynamicEnum")?;
    /// my_enum.add_value("Option1")?;
    /// ```
    pub fn new() -> Self {
        Self {
            inner: ::std::sync::Arc::new(super::runtime::get_runtime().new_type_builder()),
        }
    }

    /// Get reference to inner TypeBuilder for FFI calls.
    pub(crate) fn inner(&self) -> &::baml::TypeBuilder {
        &self.inner
    }

    // =========================================================================
    // Schema Class Accessors (1:1 with schema class names)
    // =========================================================================


    /// Access the `CommandRun` class builder.
    pub fn CommandRun(&self) -> CommandRunClassBuilder {
        CommandRunClassBuilder::new(
            self.inner.get_class("CommandRun")
                .expect("class CommandRun is defined in schema")
        )
    }


    /// Access the `HarnessBudget` class builder.
    pub fn HarnessBudget(&self) -> HarnessBudgetClassBuilder {
        HarnessBudgetClassBuilder::new(
            self.inner.get_class("HarnessBudget")
                .expect("class HarnessBudget is defined in schema")
        )
    }


    /// Access the `HarnessOutputs` class builder.
    pub fn HarnessOutputs(&self) -> HarnessOutputsClassBuilder {
        HarnessOutputsClassBuilder::new(
            self.inner.get_class("HarnessOutputs")
                .expect("class HarnessOutputs is defined in schema")
        )
    }


    /// Access the `HarnessResult` class builder.
    pub fn HarnessResult(&self) -> HarnessResultClassBuilder {
        HarnessResultClassBuilder::new(
            self.inner.get_class("HarnessResult")
                .expect("class HarnessResult is defined in schema")
        )
    }


    /// Access the `QaVerdict` class builder.
    pub fn QaVerdict(&self) -> QaVerdictClassBuilder {
        QaVerdictClassBuilder::new(
            self.inner.get_class("QaVerdict")
                .expect("class QaVerdict is defined in schema")
        )
    }


    /// Access the `SafetyBounds` class builder.
    pub fn SafetyBounds(&self) -> SafetyBoundsClassBuilder {
        SafetyBoundsClassBuilder::new(
            self.inner.get_class("SafetyBounds")
                .expect("class SafetyBounds is defined in schema")
        )
    }


    /// Access the `SignalTelemetry` class builder.
    pub fn SignalTelemetry(&self) -> SignalTelemetryClassBuilder {
        SignalTelemetryClassBuilder::new(
            self.inner.get_class("SignalTelemetry")
                .expect("class SignalTelemetry is defined in schema")
        )
    }


    /// Access the `SwarmVote` class builder.
    pub fn SwarmVote(&self) -> SwarmVoteClassBuilder {
        SwarmVoteClassBuilder::new(
            self.inner.get_class("SwarmVote")
                .expect("class SwarmVote is defined in schema")
        )
    }


    // =========================================================================
    // Schema Enum Accessors (1:1 with schema enum names)
    // =========================================================================


    /// Access the `AgentRole` enum builder.
    pub fn AgentRole(&self) -> AgentRoleEnumBuilder {
        AgentRoleEnumBuilder::new(
            self.inner.get_enum("AgentRole")
                .expect("enum AgentRole is defined in schema")
        )
    }


    /// Access the `AutonomyMode` enum builder.
    pub fn AutonomyMode(&self) -> AutonomyModeEnumBuilder {
        AutonomyModeEnumBuilder::new(
            self.inner.get_enum("AutonomyMode")
                .expect("enum AutonomyMode is defined in schema")
        )
    }


    /// Access the `BelnapState` enum builder.
    pub fn BelnapState(&self) -> BelnapStateEnumBuilder {
        BelnapStateEnumBuilder::new(
            self.inner.get_enum("BelnapState")
                .expect("enum BelnapState is defined in schema")
        )
    }


    /// Access the `BudgetTier` enum builder.
    pub fn BudgetTier(&self) -> BudgetTierEnumBuilder {
        BudgetTierEnumBuilder::new(
            self.inner.get_enum("BudgetTier")
                .expect("enum BudgetTier is defined in schema")
        )
    }


    /// Access the `CommandStatus` enum builder.
    pub fn CommandStatus(&self) -> CommandStatusEnumBuilder {
        CommandStatusEnumBuilder::new(
            self.inner.get_enum("CommandStatus")
                .expect("enum CommandStatus is defined in schema")
        )
    }


    /// Access the `HarnessLane` enum builder.
    pub fn HarnessLane(&self) -> HarnessLaneEnumBuilder {
        HarnessLaneEnumBuilder::new(
            self.inner.get_enum("HarnessLane")
                .expect("enum HarnessLane is defined in schema")
        )
    }


    // =========================================================================
    // Primitive Types (all infallible)
    // =========================================================================

    /// Get the string type.
    pub fn string(&self) -> ::baml::TypeDef {
        self.inner.string()
    }

    /// Get the int type.
    pub fn int(&self) -> ::baml::TypeDef {
        self.inner.int()
    }

    /// Get the float type.
    pub fn float(&self) -> ::baml::TypeDef {
        self.inner.float()
    }

    /// Get the bool type.
    pub fn bool(&self) -> ::baml::TypeDef {
        self.inner.bool()
    }

    /// Get the null type.
    pub fn null(&self) -> ::baml::TypeDef {
        self.inner.null()
    }

    // =========================================================================
    // Literal Types (all infallible)
    // =========================================================================

    /// Create a literal string type.
    pub fn literal_string(&self, value: &str) -> ::baml::TypeDef {
        self.inner.literal_string(value)
    }

    /// Create a literal int type.
    pub fn literal_int(&self, value: i64) -> ::baml::TypeDef {
        self.inner.literal_int(value)
    }

    /// Create a literal bool type.
    pub fn literal_bool(&self, value: bool) -> ::baml::TypeDef {
        self.inner.literal_bool(value)
    }

    // =========================================================================
    // Composite Types (all infallible)
    // =========================================================================

    /// Create a list type.
    pub fn list(&self, inner: &::baml::TypeDef) -> ::baml::TypeDef {
        self.inner.list(inner)
    }

    /// Create an optional type.
    pub fn optional(&self, inner: &::baml::TypeDef) -> ::baml::TypeDef {
        self.inner.optional(inner)
    }

    /// Create a map type.
    pub fn map(&self, key: &::baml::TypeDef, value: &::baml::TypeDef) -> ::baml::TypeDef {
        self.inner.map(key, value)
    }

    /// Create a union type.
    pub fn union(&self, types: &[&::baml::TypeDef]) -> ::baml::TypeDef {
        self.inner.union(types)
    }

    // =========================================================================
    // Schema Operations (fallible)
    // =========================================================================

    /// Add BAML schema definitions.
    pub fn add_baml(&self, baml_source: &str) -> ::std::result::Result<(), ::baml::BamlError> {
        self.inner.add_baml(baml_source)
    }

    /// Print the TypeBuilder state for debugging.
    pub fn print(&self) -> ::std::string::String {
        self.inner.print()
    }

    // =========================================================================
    // Dynamic Enum Operations
    // =========================================================================

    /// Add a new dynamic enum.
    pub fn add_enum(&self, name: &str) -> ::std::result::Result<::baml::EnumBuilder, ::baml::BamlError> {
        self.inner.add_enum(name)
    }

    /// Get an enum by name (returns None if not found).
    pub fn get_enum(&self, name: &str) -> ::std::option::Option<::baml::EnumBuilder> {
        self.inner.get_enum(name)
    }

    /// List all enums.
    pub fn list_enums(&self) -> ::std::vec::Vec<::baml::EnumBuilder> {
        self.inner.list_enums()
    }

    // =========================================================================
    // Dynamic Class Operations
    // =========================================================================

    /// Add a new dynamic class.
    pub fn add_class(&self, name: &str) -> ::std::result::Result<::baml::ClassBuilder, ::baml::BamlError> {
        self.inner.add_class(name)
    }

    /// Get a class by name (returns None if not found).
    pub fn get_class(&self, name: &str) -> ::std::option::Option<::baml::ClassBuilder> {
        self.inner.get_class(name)
    }

    /// List all classes.
    pub fn list_classes(&self) -> ::std::vec::Vec<::baml::ClassBuilder> {
        self.inner.list_classes()
    }
}

impl ::std::default::Default for TypeBuilder {
    fn default() -> Self {
        Self::new()
    }
}

impl ::std::fmt::Debug for TypeBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.debug_struct("TypeBuilder")
            .field("state", &self.print())
            .finish()
    }
}