# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (8)
# #########################################################################

class CommandRun(BaseModel):
    command: typing.Optional[str] = None
    status: typing.Optional[types.CommandStatus] = None
    log: typing.Optional[str] = None

class HarnessBudget(BaseModel):
    tier: typing.Optional[types.BudgetTier] = None
    max_total_tokens: typing.Optional[int] = None
    max_model_calls: typing.Optional[int] = None
    max_retries: typing.Optional[int] = None
    max_runner_minutes: typing.Optional[int] = None
    max_cost_usd: typing.Optional[float] = None
    approval_required_above_usd: typing.Optional[float] = None

class HarnessOutputs(BaseModel):
    branch: typing.Optional[str] = None
    pr: typing.Optional[str] = None
    diff_summary: typing.Optional[str] = None
    validation_log: typing.Optional[str] = None

class HarnessResult(BaseModel):
    job_id: typing.Optional[str] = None
    issue: typing.Optional[str] = None
    lane: typing.Optional[types.HarnessLane] = None
    autonomy_mode: typing.Optional[types.AutonomyMode] = None
    provider: typing.Optional[str] = None
    workspace: typing.Optional[str] = None
    context_bundle_sha: typing.Optional[str] = None
    prompt_pack_version: typing.Optional[str] = None
    budget: typing.Optional["HarnessBudget"] = None
    commands_run: typing.List["CommandRun"]
    changed_files: typing.List[str]
    outputs: typing.Optional["HarnessOutputs"] = None
    observations: typing.List[str]
    decision: typing.Optional[str] = None
    stop_reason: typing.Optional[str] = None
    risk_notes: typing.List[str]

class QaVerdict(BaseModel):
    verdict_id: typing.Optional[str] = None
    loop_id: typing.Optional[str] = None
    verdict: typing.Optional[str] = None
    votes: typing.List["SwarmVote"]
    rationale: typing.Optional[str] = None
    resolved_at: typing.Optional[str] = None

class SafetyBounds(BaseModel):
    thd_max: typing.Optional[float] = None
    std_dev_max: typing.Optional[float] = None
    pure_sine_std_dev: typing.Optional[float] = None

class SignalTelemetry(BaseModel):
    mean: typing.Optional[float] = None
    std_dev: typing.Optional[float] = None
    thd: typing.Optional[float] = None

class SwarmVote(BaseModel):
    agent_id: typing.Optional[str] = None
    role: typing.Optional[types.AgentRole] = None
    value: typing.Optional[types.BelnapState] = None
    reason: typing.Optional[str] = None
    self_trust: typing.Optional[float] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
