# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (6)
# #########################################################################

class AgentRole(str, Enum):
    Generator = "Generator"
    Auditor = "Auditor"
    Architect = "Architect"
    Integrator = "Integrator"

class AutonomyMode(str, Enum):
    Observe = "Observe"
    Draft = "Draft"
    Patch = "Patch"
    Pr = "Pr"
    Harvest = "Harvest"

class BelnapState(str, Enum):
    TrueVal = "TrueVal"
    Probable = "Probable"
    Unknown = "Unknown"
    Doubtful = "Doubtful"
    FalseVal = "FalseVal"
    Contradictory = "Contradictory"

class BudgetTier(str, Enum):
    FreeLocal = "FreeLocal"
    CheapHosted = "CheapHosted"
    PaidAgent = "PaidAgent"
    ManualApproval = "ManualApproval"

class CommandStatus(str, Enum):
    Passed = "Passed"
    Failed = "Failed"
    Timeout = "Timeout"
    Blocked = "Blocked"

class HarnessLane(str, Enum):
    Explore = "Explore"
    Shape = "Shape"
    Loop = "Loop"
    Verify = "Verify"
    Govern = "Govern"

# #########################################################################
# Generated classes (8)
# #########################################################################

class CommandRun(BaseModel):
    command: str
    status: CommandStatus
    log: typing.Optional[str] = None

class HarnessBudget(BaseModel):
    tier: BudgetTier
    max_total_tokens: int
    max_model_calls: int
    max_retries: int
    max_runner_minutes: int
    max_cost_usd: float
    approval_required_above_usd: float

class HarnessOutputs(BaseModel):
    branch: typing.Optional[str] = None
    pr: typing.Optional[str] = None
    diff_summary: typing.Optional[str] = None
    validation_log: typing.Optional[str] = None

class HarnessResult(BaseModel):
    job_id: str
    issue: str
    lane: HarnessLane
    autonomy_mode: AutonomyMode
    provider: str
    workspace: str
    context_bundle_sha: str
    prompt_pack_version: str
    budget: "HarnessBudget"
    commands_run: typing.List["CommandRun"]
    changed_files: typing.List[str]
    outputs: "HarnessOutputs"
    observations: typing.List[str]
    decision: str
    stop_reason: str
    risk_notes: typing.List[str]

class QaVerdict(BaseModel):
    verdict_id: str
    loop_id: str
    verdict: str
    votes: typing.List["SwarmVote"]
    rationale: str
    resolved_at: str

class SafetyBounds(BaseModel):
    thd_max: float
    std_dev_max: float
    pure_sine_std_dev: float

class SignalTelemetry(BaseModel):
    mean: float
    std_dev: float
    thd: float

class SwarmVote(BaseModel):
    agent_id: str
    role: AgentRole
    value: BelnapState
    reason: str
    self_trust: float

# #########################################################################
# Generated type aliases (0)
# #########################################################################
