# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CommandRun": types.CommandRun,
    "stream_types.CommandRun": stream_types.CommandRun,

    "types.HarnessBudget": types.HarnessBudget,
    "stream_types.HarnessBudget": stream_types.HarnessBudget,

    "types.HarnessOutputs": types.HarnessOutputs,
    "stream_types.HarnessOutputs": stream_types.HarnessOutputs,

    "types.HarnessResult": types.HarnessResult,
    "stream_types.HarnessResult": stream_types.HarnessResult,

    "types.QaVerdict": types.QaVerdict,
    "stream_types.QaVerdict": stream_types.QaVerdict,

    "types.SafetyBounds": types.SafetyBounds,
    "stream_types.SafetyBounds": stream_types.SafetyBounds,

    "types.SignalTelemetry": types.SignalTelemetry,
    "stream_types.SignalTelemetry": stream_types.SignalTelemetry,

    "types.SwarmVote": types.SwarmVote,
    "stream_types.SwarmVote": stream_types.SwarmVote,


    "types.AgentRole": types.AgentRole,

    "types.AutonomyMode": types.AutonomyMode,

    "types.BelnapState": types.BelnapState,

    "types.BudgetTier": types.BudgetTier,

    "types.CommandStatus": types.CommandStatus,

    "types.HarnessLane": types.HarnessLane,

}